import React, { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Article, ArticleCategory } from '../types';
import { saveArticle, uploadImageToStorage } from '../services/data';
import { generateArticleContent } from '../services/geminiService';
import { Sparkles, Save, Upload, AlertCircle, X, Image as ImageIcon, Loader } from 'lucide-react';

const Admin: React.FC = () => {
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState('');
  
  // Form State
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState<ArticleCategory>(ArticleCategory.CYBERSECURITY);
  const [content, setContent] = useState('');
  const [excerpt, setExcerpt] = useState('');
  const [author, setAuthor] = useState('Admin');
  const [imageUrl, setImageUrl] = useState(`https://picsum.photos/seed/${Date.now()}/800/600`);
  const [aiTopic, setAiTopic] = useState('');

  // Upload State
  const [isUploadModalOpen, setIsUploadModalOpen] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // AI Generation Handler
  const handleGenerate = async () => {
    if (!aiTopic) return;
    setIsLoading(true);
    setError('');
    
    try {
      const generated = await generateArticleContent(aiTopic, category);
      setTitle(generated.title);
      setExcerpt(generated.excerpt);
      setContent(generated.content);
      // Randomize image to feel fresh
      setImageUrl(`https://picsum.photos/seed/${aiTopic.replace(/\s/g, '')}/800/600`);
    } catch (err) {
      setError('Falha na conexão com IA. Verifique a configuração da chave API.');
    } finally {
      setIsLoading(false);
    }
  };

  // Image Upload Handler
  const processFile = async (file: File) => {
    // Basic validation
    if (!file.type.startsWith('image/')) {
      setError('Por favor, selecione apenas arquivos de imagem.');
      return;
    }

    setIsUploading(true);
    setError('');

    try {
      const uploadedUrl = await uploadImageToStorage(file);
      setImageUrl(uploadedUrl);
      setIsUploadModalOpen(false);
    } catch (err: any) {
      console.error(err);
      setError(`Erro ao enviar imagem: ${err.message}`);
    } finally {
      setIsUploading(false);
    }
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      processFile(file);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    setError('');

    try {
      const newArticle: Article = {
        // ID should be generated by DB usually, but for upsert we can generate one if it's new
        // For Supabase, if we send ID it uses it, if not (and we set default in DB) it generates.
        // For simplicity, we generate UUID v4 here.
        id: crypto.randomUUID(),
        title,
        category,
        content,
        excerpt,
        author,
        date: new Date().toISOString(),
        imageUrl,
        readTime: `${Math.ceil(content.split(' ').length / 200)} min`,
        featured: false // Default
      };
      
      await saveArticle(newArticle);
      navigate('/');
    } catch (err: any) {
      setError('Falha ao salvar o artigo. Tente novamente.');
      console.error(err);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="container mx-auto max-w-4xl px-4 py-12 text-gray-800">
      <div className="mb-8 border-b border-dark-700 pb-6">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Editor / Conexão Segura</h1>
        <p className="text-gray-500 font-mono text-sm">Crie novos relatórios de inteligência manualmente ou usando assistência de IA.</p>
      </div>

      {error && (
        <div className="mb-6 flex items-center gap-2 rounded bg-red-50 border border-red-200 p-4 text-red-600">
          <AlertCircle size={20} />
          {error}
        </div>
      )}

      {/* AI Assistant Section */}
      <div className="mb-8 rounded-xl border border-cyber-500/30 bg-cyber-50 p-6">
        <div className="mb-4 flex items-center gap-2">
          <Sparkles className="text-cyber-600" size={20} />
          <h3 className="font-bold text-gray-900">Gerador de Conteúdo IA</h3>
        </div>
        <div className="flex flex-col gap-4 sm:flex-row">
          <input 
            type="text" 
            value={aiTopic}
            onChange={(e) => setAiTopic(e.target.value)}
            placeholder="Digite um tópico (ex: 'Tendências de Phishing 2024')" 
            className="flex-1 rounded-lg border border-dark-700 bg-white px-4 py-2 focus:border-cyber-500 focus:outline-none"
          />
          <button 
            onClick={handleGenerate}
            disabled={isLoading || !aiTopic}
            className="flex items-center justify-center gap-2 rounded-lg bg-cyber-600 px-6 py-2 font-medium text-white hover:bg-cyber-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {isLoading ? 'Gerando...' : 'Gerar Rascunho'}
          </button>
        </div>
        <p className="mt-2 text-xs text-gray-500">Desenvolvido com modelos Gemini 2.5 Flash.</p>
      </div>

      {/* Main Form */}
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="grid gap-6 md:grid-cols-2">
          <div>
            <label className="mb-2 block text-sm font-medium text-gray-600">Título</label>
            <input 
              required
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full rounded-lg border border-dark-700 bg-white px-4 py-2 focus:border-cyber-500 focus:outline-none"
            />
          </div>
          <div>
             <label className="mb-2 block text-sm font-medium text-gray-600">Categoria</label>
             <select 
               value={category}
               onChange={(e) => setCategory(e.target.value as ArticleCategory)}
               className="w-full rounded-lg border border-dark-700 bg-white px-4 py-2 focus:border-cyber-500 focus:outline-none"
             >
               {Object.values(ArticleCategory).slice(1).map(c => <option key={c} value={c}>{c}</option>)}
             </select>
          </div>
        </div>

        <div>
           <label className="mb-2 block text-sm font-medium text-gray-600">Resumo</label>
           <textarea 
             rows={2}
             value={excerpt}
             onChange={(e) => setExcerpt(e.target.value)}
             className="w-full rounded-lg border border-dark-700 bg-white px-4 py-2 focus:border-cyber-500 focus:outline-none"
           />
        </div>

        <div>
           <label className="mb-2 block text-sm font-medium text-gray-600">Conteúdo (Markdown)</label>
           <textarea 
             required
             rows={12}
             value={content}
             onChange={(e) => setContent(e.target.value)}
             className="w-full rounded-lg border border-dark-700 bg-white px-4 py-2 font-mono text-sm focus:border-cyber-500 focus:outline-none"
           />
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          <div>
            <label className="mb-2 block text-sm font-medium text-gray-600">URL da Imagem</label>
            <div className="flex gap-2">
              <input 
                value={imageUrl}
                onChange={(e) => setImageUrl(e.target.value)}
                className="flex-1 rounded-lg border border-dark-700 bg-white px-4 py-2 focus:border-cyber-500 focus:outline-none text-xs"
                placeholder="https://..."
              />
              <button 
                type="button" 
                onClick={() => setIsUploadModalOpen(true)}
                className="flex items-center gap-2 rounded-lg border border-dark-700 bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200 transition-colors"
              >
                <Upload size={16} />
                <span className="hidden sm:inline">Carregar Imagem</span>
              </button>
            </div>
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium text-gray-600">Autor</label>
            <input 
              value={author}
              onChange={(e) => setAuthor(e.target.value)}
              className="w-full rounded-lg border border-dark-700 bg-white px-4 py-2 focus:border-cyber-500 focus:outline-none"
            />
          </div>
        </div>

        <div className="flex justify-end pt-6">
          <button 
            type="submit"
            disabled={isSaving}
            className="flex items-center gap-2 rounded-lg bg-gray-900 px-8 py-3 font-bold text-white hover:bg-gray-800 transition-colors disabled:opacity-70 disabled:cursor-not-allowed"
          >
            {isSaving ? <Loader className="animate-spin" size={18} /> : <Save size={18} />}
            {isSaving ? 'Publicando...' : 'Publicar Protocolo'}
          </button>
        </div>
      </form>

      {/* Upload Modal */}
      {isUploadModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
          <div className="w-full max-w-md rounded-xl bg-white p-6 shadow-2xl animate-fade-in-up">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-lg font-bold text-gray-900">Carregar Imagem para Nuvem</h3>
              <button 
                onClick={() => !isUploading && setIsUploadModalOpen(false)} 
                className="text-gray-500 hover:text-red-500 transition-colors"
                disabled={isUploading}
              >
                <X size={20} />
              </button>
            </div>
            
            <div 
              className={`relative flex h-56 flex-col items-center justify-center rounded-lg border-2 border-dashed transition-all
                ${isUploading ? 'border-cyber-500 bg-cyber-50' : 'border-gray-300 bg-gray-50 hover:bg-gray-100'}`}
              onDragOver={(e) => {
                e.preventDefault();
                e.stopPropagation();
              }}
              onDrop={(e) => {
                e.preventDefault();
                e.stopPropagation();
                if (!isUploading) {
                  const file = e.dataTransfer.files?.[0];
                  if (file) processFile(file);
                }
              }}
            >
              {isUploading ? (
                  <div className="flex flex-col items-center gap-3 text-cyber-700 animate-pulse">
                      <Loader className="animate-spin" size={36} />
                      <div className="text-center">
                        <span className="block text-sm font-bold">Criptografando & Enviando...</span>
                        <span className="text-xs text-cyber-600">Aguarde a confirmação do servidor</span>
                      </div>
                  </div>
              ) : (
                  <>
                      <div className="mb-3 rounded-full bg-white p-3 shadow-sm">
                        <ImageIcon className="h-8 w-8 text-gray-400" />
                      </div>
                      <p className="mb-1 text-sm font-medium text-gray-700">Arraste e solte sua imagem aqui</p>
                      <p className="mb-4 text-xs text-gray-500">ou</p>
                      <button 
                        type="button"
                        onClick={() => fileInputRef.current?.click()}
                        className="rounded-lg bg-white px-4 py-2 text-sm font-medium text-cyber-600 shadow-sm border border-gray-200 hover:border-cyber-500 hover:text-cyber-700 transition-all"
                      >
                        Selecionar do Dispositivo
                      </button>
                      <input 
                        ref={fileInputRef}
                        type="file" 
                        accept="image/*" 
                        className="hidden"
                        onChange={handleFileSelect}
                      />
                  </>
              )}
            </div>
            <div className="mt-4 flex justify-between items-center text-xs text-gray-400 font-mono">
              <span>Formatos: PNG, JPG, WEBP</span>
              <span>Max: 5MB</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Admin;